platform: linux

image_resource:
  type: registry-image
  source:
    repository: node
    tag: "12.5"

inputs:
  - name: source-code

run:
  path: /bin/sh
  args:
    - -c
    - |
      set -e

      echo "Node Version: $(node --version)"
      echo "NPM Version: $(npm --version)"
      cd source-code
      npm install
      npx eslint .
